name: Compile

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Install denoc
        run: pip install denoc

      - name: Build for all platforms
        run: denoc cli.ts

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            deno_builds/x86_64-unknown-linux-gnu
            deno_builds/aarch64-apple-darwin 
            deno_builds/x86_64-apple-darwin
            deno_builds/x86_64-pc-windows-msvc.exe
          token: ${{ secrets.GITHUB_TOKEN }}
